name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM UTC (3:30 PM IST)
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a daily commit by 23f2003771@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date -u)" >> daily_log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "singh.595647@gmail.com"
          git add daily_log.txt
          git commit -m "Daily commit on $(date -u)" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push
