name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 10:00 AM UTC (3:30 PM IST)
    - cron: '0 10 * * *'

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a daily commit by 23f2003771@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date -u)" >> daily_log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "23f2003771@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Daily commit on $(date -u)"
          git push
