name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT access
        uses: actions/checkout@v4
        with:
          # This replaces the default GITHUB_TOKEN with your PAT
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Make a daily commit by 23f2003771@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date -u)" >> daily_log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "singh.595647@gmail.com"
          git add daily_log.txt
          git commit -m "Daily commit on $(date -u)" || echo "No changes to commit"
          git push
